### ISSUE TITLE
Monte Carlo 2, after problem 3, up through problem 4

### ISSUE THREAD

**Issue by tannert** [Foundations-of-Applied-Mathematics/Labs#1019]
- 'thusfar' needs to be 'thus far'

- Problem 4 was really hard.  I didn’t have a clue where to start or how to use the random variable that multivariate_random returns until I looked at the example code just above problem 2 and used that.  However, the np.sum trick you pulled there doesn’t play nicely with two-dimensional arrays so finally I had to revert to an iterative solution.

- The last paragraph of the problem description could just as well be replaced with ‘look at the documentation for ss.multivariate_random’ and would take up a lot less space.

**Comment by swsuggs** [comment]
Knowing the correct answer to problem 4 would be helpful.  I got a number but I don't think it's right.  I am a little confused, and more so since reading what tannert wrote.  The thing we're summing (f * h / g) shouldn't be two-dimensional should it?  Also, irrelevant general wondering, why does everyone always use np.sum, when the built-in plain old sum() works just fine?

**Comment by tkchris93** [comment]
@tannert @swsuggs  Right before problem 4, I have added a fourth step that will hopefully add some clarification. Originally I had left the correct answer off this problem because if you're given this problem in the real world, you won't be given the real answer by your boss. I'm totally open to input, though.

@swsuggs The reason people use np.sum() is because you can define axes to sum across. Also, np.sum() is way faster than sum(), so it's a good habit to have.

**Comment by swsuggs** [comment]
@tkchris93 True, and in the real world I would spend as long as it takes doing endless tests to verify my algorithm was working.  When it's one problem amidst all the other homework I have, I have less desire and less time to do that.  However I get the point and I'm fine if you leave it out.

**Comment by swsuggs** [comment]
I discovered what was giving me a funny answer was that I had copied the joint normal formula wrong.  Other than that I had it all along, so the problem must have been clear after all!  I would just agree with tannert, you ought to remove the commas preceding the equations.  You do it twice before problem one, once between one and two, and twice after problem four.

**Comment by shanemcq18** [comment]
@jmorrise is this feedback out-of-date or still helpful?

**Comment by jmorrise** [comment]
@shanemcq18 Still somewhat helpful, although it sounds like Tanner sorted out most of it.
