### ISSUE TITLE
Linear Transformations / Systems

### ISSUE THREAD

**Issue by shanemcq18** [Foundations-of-Applied-Mathematics/Labs#1165]
Changing Complexity and Linear/Affine Transformations labs to . . .

### Linear Transformations
-  Linear Transformations
    - [x] Definition
    - [x] Check that notation aligns with the book
    - [x] Explain `horse.npy` and how to plot it.
    - [x] Stretches / Dilations
    - [x] Shears
    - [x] Rotations
    - [x] Reflections
    - [x] **Problem**: Use linear transformations to alter arrays like `horse.npy`
    - [x] Compositions
- Affine Transformations
    - [x] Definition
    - [x] Translations
    - [x] **Problem**: Moon orbiting the earth orbiting the sun 
- Timing Linear Algebra Algorithms
    - [x] `time` and `timeit` modules
    - [x] Example: Timing matrix generation.
    - [x] **Problem**: Matrix-vector and matrix-matrix multiplication w/ lists of lists.
    - [x] Explain lin-log and log-log plots.
    - [x] **Problem**: Compare previous approach to NumPy operations. Behold the speed boost!
    - [x] A note about Caching (explains non-smooth curve w/ NumPy).
- Additional Material
    - [x] Suggest organizing the linear transformations into a class
    - [x] Animating the orbit problem
    - A [good] note about celestial mechanics
    - A note about using formal profilers (?)

### Linear Systems
- LU Decomposition
    - [x] Row Operations
    - [x] **(Easy) Problem**: REF
    - [x] **Problem**: Implement the LU decomposition
    - [x] **Problem**: Use the LU decomposition and back substitution to solve linear systems.
- Formally introduce SciPy (`linalg`, `sparse`)
    - [x] List common `la` functions: `det()`,`eig()`, `inv()`, `norm()`, `solve()`
    - [x] Demonstrate `la.lu_factor()` and `la.lu_solve()`
    - [x] **Problem**: Time `la.inv()`, `la.solve()`, and LU funcs to solve _A_**x** = **b**
- Sparse Matrices
    - [x] Matrix types and their advantages
    - [x] Sparse matrix construction
    - [x] **Problem**: Construct a huge sparse matrix (?)
    - [x] Sparse matrix operations (addition, scalar multiplication, matrix multiplication, system solving)
    - [x] **Problem**: Solve a huge linear system with `sparse.spsolve()` or something?
- Additional Material
    - [x] More robust REF
    - [x] Instead of row swaps, talk about "partial pivoting" (see comment below)
    - [x] Using the LU decomposition to find the determinant of a matrix
    - [x] Cholesky Factorization

**Comment by shanemcq18** [comment]
Instead of cutting out the particle trajectory problem, I turned it into a [very rough] solar system simulation. If we don't move things around, that problem makes the lab just the right length.

**Comment by shanemcq18** [comment]
These two labs cover four topics:
- Timing code and discovering algorithm complexity empirically
- Linear transformations (horse pictures)
- Solving _A_**x** = **b** via the LU decomposition
- SciPy tools for solving _A_**x**=**b**, including `scipy.linalg` and `scipy.sparse`

The last two points go together pretty well, but it's a little difficult to get the first two points to mesh (it made it really hard to write a good objective statement for Linear Transformations). Any thoughts on this, @montu-byu?

**Comment by montu-byu** [comment]
What if we were to flip the topics in the first lab.  That is: First we define a linear transformation and have them do some stuff.  Then we introduce timing code and discovering algorithm complexity empirically. The objective statement for the lab could read something like:

Linear transformations are the most basic and essential operations in vector space theory; we visually explore how linear transformations alter points in $\mathbb{R}^2$. Then, using linear transformations as an example, we explore one of the most important questions in scientific computing is ``How long will a computer take to execute this algorithm?'' In this lab we experiment with timing of algorithms and determine why NumPy is a good option for performing numerical linear algebra.

If we do this rearrangement I think we should rename the lab linear transformations and beginning algorithmic complexity (or something like that).  Since half the lab is essentially complexity, we should say that.

**Comment by montu-byu** [comment]
For the second lab...

I'm probably getting on my soap box a little too much, but if you are going to tell them how Gaussian elimination fails, you should also tell them how to fix it (probably in the optional section).  Rather than introducing row swaps as you do, you should introduce them in the context of Gaussian elimination with partial pivoting.  Then you can make one of my more favorite observations attributed to Wilkinson about using Gaussian elimination with complete pivoting

"Anyone that unlucky has already been run over by a bus!"

**Comment by shanemcq18** [comment]
Some notes for possible future edits:
- Linear Transformations
    - The note on caching (right before Additional Material) could be improved with a little picture depicting how the times for NumPy operations increase, which reveals where the cache lines are. I couldn't get a very clear picture without using C code like in the old caching lab.
    - The little blurb on celestial mechanics could be improved. I'm mostly hoping to impress students with the fact that the 2-body problem is completely solvable, but that the n-body problem is, in general, impossible (without getting overly technical about it).
    - We could add another little blurb or note about how Python has formal profilers for timing code, maybe with examples. I think about this more after I've gone through the Profiling lab.
- Linear Systems
    - Would it be beneficial to move the section on partial pivoting out of Addition Material and into the main lab? This could be an option if the students find the lab too easy.
    - The problem where you construct a diagonal sparse matrix could be replaced with a matrix that the students need for the next lab (we don't even have to tell them that that's what they're doing).

As always, the objective statements could use a good proofread from the professors.

Closing this issue for now.
